spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=utf-8&useSSL=false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  context-path: /zjut
socketIO:
  hostName: localhost
  port: 8081